# Generated by Django 2.0.2 on 2018-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('pronounciation', models.CharField(blank=True, max_length=255, null=True)),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'words',
            },
        ),
    ]
